title: "Daniel Cuervo"
email: "danielcuervor01@gmail.com"
description: >-
  Technical portfolio

baseurl: ""
url: "https://corvo01.com"
repository: "corvo001/web"
locale: "es-ES"

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap

exclude:
  - AGENTS.md
  - Gemfile
  - Gemfile.lock
  - README.md
